Parameters:
  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: wsi

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: hmoon

Resources:
  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: "The CMK for KMS multi-region"
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable Root User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      # KeySpec: String
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: true
      PendingWindowInDays: 7
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner

  KeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: "alias/kms/replica-key"
      TargetKeyId: !Ref Key

Outputs:
  KeyArn:
    Description: "The Key Arn for multi-region replication"
    Value: !GetAtt Key.Arn
