Parameters:
  EFSName:
    Type: String
    Description: "The name for the EFS"

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "The Subnet Ids for efs network interfaces"

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "The Security Group Ids for efs network interfaces"

  SubnetCount:
    Type: Number
    Description: "Subnet, AZ Count"
    AllowedValues:
      - 2
      - 3
    Default: 2

  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: wsi

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: hmoon

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "EFS Configuration"
        Parameters:
          - EFSName
          - SecurityGroupIds
          - SubnetIds
          - SubnetCount
      - Label:
          default: "Tag configuration"
        Parameters:
          - Project
          - Owner

Conditions:
  ThirdSubnet: !Equals [!Ref SubnetCount, 3]

Resources:
  #
  # EFS - FileSystem
  #
  FileSystem:
    Type: AWS::EFS::FileSystem
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      # KmsKeyId: String
      FileSystemTags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref EFSName
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS # AFTER_7_DAYS , AFTER_14_DAYS , AFTER_30_DAYS , AFTER_60_DAYS , AFTER_90_DAYS
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      PerformanceMode: generalPurpose # generalPurpose , maxIO
      ThroughputMode: bursting # bursting , provisioned
      # ProvisionedThroughputInMibps: Double

  #
  # EFS - MountTarget
  #
  MountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      # IpAddress: String
      SecurityGroups: !Ref SecurityGroupIds
      SubnetId: !Select [0, !Ref SubnetIds]

  MountTargetB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      # IpAddress: String
      SecurityGroups: !Ref SecurityGroupIds
      SubnetId: !Select [1, !Ref SubnetIds]

  MountTargetC:
    Type: AWS::EFS::MountTarget
    Condition: ThirdSubnet
    Properties:
      FileSystemId: !Ref FileSystem
      # IpAddress: String
      SecurityGroups: !Ref SecurityGroupIds
      SubnetId: !Select [2, !Ref SubnetIds]
