Parameters:
  LatestAMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
    AllowedValues:
      - /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
      - /aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64
      - /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64
      - /aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-arm64
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-x86_64-ebs
      - /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-ebs
      - /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2
      - /aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-s3
      - /aws/service/ami-amazon-linux-latest/amzn-ami-minimal-hvm-x86_64-ebs
      - /aws/service/ami-amazon-linux-latest/amzn-ami-minimal-hvm-x86_64-s3

  BastionName:
    Type: String
    Default: 'bastion'

  InstanceType:
    Type: String
    Default: t3.micro


Resources:
  BastionInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAMI
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PublicSubnetA
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      UserData:
        Fn::Base64: !Sub | 
          #!/bin/bash
          echo "${AWS::StackId}" > /var/lll.log
          echo 'Skill53' | passwd --stdin ec2-user
          sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
          echo 'Port 43822' >> /etc/ssh/sshd_config
          systemctl restart sshd
          systemctl enable sshd 
      Tags:
        - Key: Name
          Value:  !Ref BastionName

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "The security group for application"
      GroupName: !Sub "${NamePrefix}-bastion-sg"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${NamePrefix}-bastion-sg"
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner

  BastionSecurityGroupIngressALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "SSH Allow"
      GroupId: !Ref BastionSecurityGroup
      # SourceSecurityGroupId: !Ref ALBSecurityGroup
      # SourcePrefixListId: pl-63a5400a # you can check prefixlistID in console.
      CidrIp: 0.0.0.0/0
      IpProtocol: -1 # -1(all) , tcp , udp , icmp , icmpv6
      FromPort: 22
      ToPort: 22
