Parameters:
  ALBName:
    Type: String
    Description: "The name for the application load balancer"

  ALBScheme:
    Type: String
    Description: "Scheme of the ALB"
    AllowedValues:
      - "internal"
      - "internet-facing"

  ALBAccessLogEnable:
    Type: String
    Description: "Whether enable access log or not"
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  ALBAccessLogBucket:
    Type: String
    Description: "Bucket name where logs are stored. Bucket policy must allow putObject for logging"
    Default: "bucket-name"

  TargetGroupName:
    Type: String
    Description: "The name for the target group"

  TargetType:
    Type: String
    Description: "The target group type. Instance or IP"
    AllowedValues:
      - "instance"
      - "ip"

  TargetPort:
    Type: String
    Description: "The port of the target"
    Default: 80

  HealthCheckPath:
    Type: String
    Description: "Target group health check path"
    Default: "/"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "The vpc id for application load balancer"

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "The subnet ids for application load balancer"

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "The security group ids for application load balancer"

  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: wsi

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: hmoon

Conditions:
  EnableALBAccessLog: !Equals [!Ref ALBAccessLogEnable, "true"]

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC tag configuration"
        Parameters:
          - Project
          - Owner
      - Label:
          default: "ALB Configuration"
        Parameters:
          - ALBName
          - ALBScheme
          - TargetGroupName
          - TargetType
          - TargetPort
          - HealthCheckPath
          - ALBAccessLogEnable
          - ALBAccessLogBucket
      - Label:
          default: "ALB Network Configuration"
        Parameters:
          - VpcId
          - SubnetIds
          - SecurityGroupIds
Resources:
  #
  # ELBv2 - Target Group
  #
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckPort: !Ref TargetPort
      HealthCheckProtocol: HTTP # HTTP , HTTPS
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      IpAddressType: ipv4 # ipv4 , ipv6
      Name: !Ref TargetGroupName
      Port: !Ref TargetPort
      Protocol: HTTP # HTTP , HTTPS
      ProtocolVersion: HTTP1 # GRPC , HTTP1 , HTTP2
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
      TargetType: !Ref TargetType # instance , ip , lambda , alb
      VpcId: !Ref VpcId

  #
  # ELBv2 - Internet-facing ALB
  #
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref ALBName
      Type: application # application , network , gateway
      Scheme: !Ref ALBScheme # internal , internet-facing
      IpAddressType: ipv4 # ipv4 , ipv6
      LoadBalancerAttributes:
        - Key: routing.http2.enabled
          Value: true
        - Key: access_logs.s3.enabled
          Value: !Ref ALBAccessLogEnable
        - "Fn::If":
            - EnableALBAccessLog
            - Key: access_logs.s3.bucket
              Value: !Ref ALBAccessLogBucket
            - !Ref "AWS::NoValue"
      SecurityGroups: !Ref SecurityGroupIds
      Subnets: !Ref SubnetIds
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner

  #
  # ELBv2 - Listener
  #
  ApplicationLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      # Certificates:
      #   - CertificateArn: String
      # SslPolicy: String
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            MessageBody: "Content not found"
            StatusCode: "404"
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP # GENEVE , HTTP , HTTPS , TCP , TCP_UDP , TLS , UDP
  ListenerRule1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /*
      ListenerArn: !Ref ApplicationLoadBalancerListener
      Priority: 1
  # ListenerRule2:
  #   Type: AWS::ElasticLoadBalancingV2::ListenerRule
  #   Properties:
  #     Actions:
  #       - Type: fixed-response
  #         FixedResponseConfig:
  #           ContentType: text/plain
  #           MessageBody: "Content not found"
  #           StatusCode: "404"
  #     Conditions:
  #       - Field: path-pattern
  #         PathPatternConfig:
  #           Values:
  #             - /health
  #             - /healthcheck
  #     ListenerArn: !Ref ApplicationLoadBalancerListener
  #     Priority: 2
