version: 0.2

phases:
  pre_build:
    commands:
      - curl --silent --location -o ./argocd https://github.com/argoproj/argo-cd/releases/download/v2.4.7/argocd-linux-amd64
      - chmod +x ./argocd
      - ./argocd login a214ee6c10b444a01813678f9b4e0b4a-1679529766.ap-northeast-2.elb.amazonaws.com --username admin --password UXcFh9W6aDmOnI0k --insecure
  build:
    commands:
      - ./argocd app sync da
      # - ./argocd app sync <APPLICAITON_NAME> --namespace <NAMESPACE>

  post_build:
    commands:
      - echo "FINISH!"