version: 0.0
os: linux
files:
  - source: /server
    destination: /opt/app
permissions:
  - object: /opt/app/server
    mode: 755
    owner: ec2-user
    group: ec2-user
file_exists_behavior: OVERWRITE # DISALLOW | OVERWRITE | RETAIN
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

