# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "stress"
          ContainerPort: 8080
        CapacityProviderStrategy:
          - Base: 0
            CapacityProvider: "us-cluster-EC2CapacityProvider-wKFzeSoxuoQQ"
            Weight: 2
